---
title: "Desk usage in Analytical Services"
author: "Thomas Hirsch"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document

params:
  start_date: "2018-03-01"
  end_date: "2018-04-01"
  report_date: "March 2018"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("data_cleaning_functions.R")
source("charting_functions.R")
source("report_configuration.R")
```


## Desk utilisation in ASD for `r params$report_date`

The following chart shows desk utilisation in ASD for March
```{r utilisation_plot, echo=FALSE, dpi = 150, fig.width=8.9, fig.height=5}
df_sum <- get_df_sum(df,start_time,end_time)
print(allocation_strategy_table(df_sum))
print(prop_daily_usage_chart(df_sum))
print(prop_weekday_usage_chart(df_sum))
print(prop_desk_usage_chart(df_sum))
print(smoothing_chart(df_sum,0.5))


## To be reworked (out of scope for this update)
# team_list <- distinct(df,category_3)
# 
# for(team in team_list) {
#   cat('\n')
#   cat('Desk utlisation for ',team,'\n')
#   team_data <- filter(df,category_3 == team)
#   df_sum <- get_df_sum(team_data,start_time,end_time)
#   print(prop_daily_usage_chart(df_sum))
#   cat('\n')
# }

```