---
title: "Desk usage Report"
author: "Thomas Hirsch"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: slidy_presentation

params:
  start_date: NULL
  end_date: NULL
  df_sum: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Desk utilisation for `r params$start_date` to `r params$end_date`

```{r summary, echo=FALSE, results='asis', dpi = 150, fig.width=8.9, fig.height=5}
df_sum <- params$df_sum

knitr::kable(allocation_strategy_table(df_sum),align=c('l','r','r'))
cat('\n\n----\n\n')
cat('## Top 10 busiest days in survey')
knitr::kable(get_peak_occupancy(df_sum))
cat('\n\n----\n\n')
print(prop_daily_usage_chart(df_sum))
cat('\n\n----\n\n')
print(prop_weekday_usage_chart(df_sum))
cat('\n\n----\n\n')
print(prop_desk_usage_chart(df_sum))
cat('\n\n----\n\n')
print(smoothing_chart(df_sum,0.5))
```

```{r team_slides, echo=FALSE, results='asis', dpi = 150, fig.width=8.9, fig.height=5}
team_list <- unique(df_sum$category_1)
for(team in team_list) {
  if(team != "N/A") {
    cat1_df_sum <- df_sum %>% filter(category_1 == team)
    
    if(length(team_list) > 1) {
      cat('\n\n----\n\n')
      cat('## Desk utilisation for ',team,' (',n_distinct(cat1_df_sum$surveydeviceid),' sensors) \n\n',sep="")
      print(prop_daily_usage_chart(cat1_df_sum))
    }
    
    cat2s <- unique(cat1_df_sum$category_2)
    for(cat2 in cat2s) {
      cat2_df_sum <- cat1_df_sum %>% filter(category_2 == cat2)
      if(length(cat2s) > 1) {
        cat('\n\n----\n\n')
        cat('## Desk utilisation for ',team," - ",cat2,' (',n_distinct(cat2_df_sum$surveydeviceid),' sensors) \n\n',sep="")
        print(prop_daily_usage_chart(cat2_df_sum))
      }
      
      cat3s <- unique(cat2_df_sum$category_3)
      for(cat3 in cat3s) {
        cat3_df_sum <- cat2_df_sum %>% filter(category_3 == cat3)
        if(length(cat2s) > 1) {
          cat('\n\n----\n\n')
          cat('## Desk utilisation for ',team,' - ',cat2,' - ',cat3,' (',n_distinct(cat3_df_sum$surveydeviceid),' sensors) \n\n',sep="")
          print(prop_daily_usage_chart(cat3_df_sum))
        }
      }
      
    }
    
  }
}

```