---
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  word_document:
    toc: true
    reference_docx: occupeye-report-reference.dotx

params:
  start_date: NULL
  end_date: NULL
  df_sum: NULL
  survey_name: NULL
  
title: "`r paste0('Desk usage report, ', params$survey_name)`"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### line break

# Desk usage report

Note: The following table of recommendations is based on data for the top-level business group. Should any action be proposed following this report then further reports should be generated at the level at which desk sharing takes place.

## Desk utilisation for `r params$start_date` to `r params$end_date`

```{r summary, echo=FALSE, results='asis', dpi = 150, fig.width=8.9, fig.height=5}
df_sum <- params$df_sum

longstay_desks <- df_sum %>% dplyr::filter(devicetype == "Longstay Desk")
non_longstay_desks <- df_sum %>% dplyr::filter(devicetype != "Longstay Desk")

if(nrow(longstay_desks) > 0) {
  cat("### Recommendation table for longstay desks:")
  
  knitr::kable(allocation_strategy_table(longstay_desks),align=c('l','r','r'))
}

if(nrow(non_longstay_desks) > 0) {
  cat("### Recommendation table for non-longstay desks: ")
  
  knitr::kable(allocation_strategy_table(non_longstay_desks),align=c('l','r','r'))
}

cat('## Top 10 busiest days in survey')
knitr::kable(get_peak_occupancy(df_sum))
print(prop_daily_usage_chart(df_sum))
cat(paste0("\n\n ",daily_usage_chart_narrative(df_sum)))
print(prop_weekday_usage_chart(df_sum))
cat(paste0("\n\n ",weekday_usage_narrative(df_sum)))
print(prop_desk_usage_chart(df_sum))
print(smoothing_chart(df_sum,0.5))
cat(paste0("\n\n ",get_smoothing_narrative(df_sum,0.5)))
```

```{r team_slides, echo=FALSE, results='asis', dpi = 150, fig.width=8.9, fig.height=5}
floor_list <- unique(df_sum$floor)

if(length(floor_list) > 1) {
  for(my_floor in floor_list) {
    floor_df_sum <- df_sum %>% dplyr::filter(floor == my_floor)
    cat('\n\n## Desk utilisation for floor ',my_floor,' (',n_distinct(floor_df_sum$survey_device_id),' sensors) \n\n',sep="")
    print(prop_daily_usage_chart(floor_df_sum))
    cat(paste0("\n\n ",daily_usage_chart_narrative(floor_df_sum)))
    
  }
}


```